Repository Sanskriti1102/Techtalksintelligenz, pull requests merged in 2024-10, with the labels that each got.

#33 Create CONTRIBUTING.md issue no #22 Resolved
  CONTRIBUTING.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#37 Add contributors automatically to Readme.md
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#47 Color change on hovering the link icons
  css/style.css
  package-lock.json
Labels: gssoc-ext, level2, hacktoberfest-accepted

#60 Created auto comment-on-close.yml
  .github/workflow/ato-comment-on-close.yml
  .github/workflow/auto-comment-on-close.yml
Labels: gssoc-ext, level1, hacktoberfest-accepted

#70 Changed the icons of twitter to X in footer as well as in we feature.
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#69 added email and google sheets functionality issue #65
  server/.env.example
  server/.gitignore
  server/controller.js
  server/package-lock.json
  server/package.json
  server/route.js
  server/server.js
Labels: gssoc-ext, level3, hacktoberfest-accepted

#74 Fix Contact Us Section Links #71
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#79 Feat 404page
  404_page/404-page.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#105 Added AI base chatbot
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#110 Grammatical error corrected.
  index.html
  single.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#109 Redesigned "We Feature On" Section
  css/style.css
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#101 Well aligned stats section with animation
  css/style.css
  index.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#114 Implement GitHub PR Issue Checker Workflow
  .github/workflow/pr-checker.yaml
Labels: gssoc-ext, level2, hacktoberfest-accepted
